import "./globals.css";
import "./style.css";
import { Nunito } from "next/font/google";
import Main from "@/components/layout/admin/main";
import Providers from "./Providers";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" color-scheme="light">
      <body className={inter.className}>
        <Providers>
          <Main title="School Management System" >
            {children}
          </Main>
        </Providers>
      </body>
    </html>
  );
}
